# Rename it to config.yaml to use it.

telegram:
  api_token: "<YOUR_BOT_TOKEN_HERE>"
  channel_id: -1001234567890


logic:
  warning_level: 5.0
  critical_level: 2.0

  cd_normal: 1d
  cd_warning: 12h
  cd_critical: 2h


api:
  host: "0.0.0.0"
  port: 8080


iot:
  callback_host: "http://your.domain.com:8080"
  wifi_ssid: "SomeSSID"
  wifi_password: "12345678"
  shared_secret: "my_shared_secret"
