import argparse
import math
import os
import tempfile
from collections.abc import Mapping, Sequence
from pathlib import Path

from backend.utils import load_config

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_CONFIG_FILE = PROJECT_ROOT / "config.yaml"
DEFAULT_TARGET_FILE = PROJECT_ROOT / "iot_code" / "private_const.py"
GENERATED_HEADER = "# This file is auto-generated by backend/sync_config.py\n"


def _constant_name(key: object) -> str:
    if not isinstance(key, str):
        raise TypeError(f"IoT configuration keys must be strings, got {type(key).__name__}")

    name = key.upper()
    if not name.isidentifier():
        raise ValueError(f"IoT configuration key {key!r} is not a valid Python identifier")
    return name


def render_iot_config(iot_config: Mapping[str, object]) -> tuple[str, list[str]]:
    lines = [GENERATED_HEADER]
    constant_names = []
    seen_names = set()

    for key, value in iot_config.items():
        constant_name = _constant_name(key)
        if constant_name in seen_names:
            raise ValueError(f"Duplicate generated constant name: {constant_name}")
        if not isinstance(value, (str, int, float, bool)):
            raise TypeError(
                f"Unsupported value type for IoT configuration key {key!r}: "
                f"{type(value).__name__}"
            )
        if isinstance(value, float) and not math.isfinite(value):
            raise ValueError(f"IoT configuration key {key!r} must contain a finite number")

        seen_names.add(constant_name)
        constant_names.append(constant_name)
        lines.append(f"{constant_name} = {value!r}\n")

    return "".join(lines), constant_names


def read_iot_config(config_path: Path) -> Mapping[str, object]:
    try:
        config = load_config(str(config_path))
    except ValueError:
        raise ValueError(f"Unable to parse YAML configuration file: {config_path}") from None
    if not isinstance(config, Mapping):
        raise TypeError("The configuration root must be a mapping")

    iot_config = config.get("iot")
    if not isinstance(iot_config, Mapping):
        raise TypeError("The configuration must contain an 'iot' mapping")
    return iot_config


def write_private_config(target_path: Path, content: str) -> None:
    target_path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path = None

    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=target_path.parent,
            prefix=f".{target_path.name}.",
            delete=False,
        ) as temporary_file:
            temporary_path = Path(temporary_file.name)
            os.chmod(temporary_path, 0o600)
            temporary_file.write(content)
            temporary_file.flush()
            os.fsync(temporary_file.fileno())

        os.replace(temporary_path, target_path)
        os.chmod(target_path, 0o600)
        temporary_path = None
    finally:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate MicroPython constants from the local IoT configuration."
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=DEFAULT_CONFIG_FILE,
        help=f"source YAML file (default: {DEFAULT_CONFIG_FILE})",
    )
    parser.add_argument(
        "--target",
        type=Path,
        default=DEFAULT_TARGET_FILE,
        help=f"generated Python file (default: {DEFAULT_TARGET_FILE})",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="validate input and report the target without writing a file",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    content, constant_names = render_iot_config(read_iot_config(args.config))
    action = "Would sync" if args.dry_run else "Synced"

    if not args.dry_run:
        write_private_config(args.target, content)

    names = ", ".join(constant_names) if constant_names else "no keys"
    print(f"{action} {len(constant_names)} IoT configuration keys to {args.target}: {names}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
